"""
Django settings for songforyou project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults are deliberately the SAFE ones, so a missing env var in production
# fails closed rather than silently shipping the permissive dev behaviour.
DEBUG = config('DEBUG', default=False, cast=bool)

# In production ALLOWED_HOSTS must be set explicitly; an empty list makes Django
# reject every request, which is the intended failure mode.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Comma-separated, scheme included, e.g. 'https://songforyou.app'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:3000',
        'http://localhost:8000',
    ]

# Render injects the service's own public hostname. Trust it automatically so
# the first deploy works before any custom domain exists - without this the very
# first request is a DisallowedHost 400, which looks like a broken deploy.
_RENDER_HOST = config('RENDER_EXTERNAL_HOSTNAME', default='')
if _RENDER_HOST:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + [_RENDER_HOST]
    CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [f'https://{_RENDER_HOST}']

# Trust the X-Forwarded-Proto header set by the reverse proxy / load balancer
# that terminates TLS in front of this app (Render, Railway, Fly, Heroku, nginx).
# Without this Django sees forwarded requests as plain HTTP and builds http://
# callback URLs, which Spotify rejects for non-localhost redirect URIs.
#
# SECURITY: only correct when the app is ALWAYS behind a proxy that sets this
# header itself. If it is ever reachable directly, a client can forge the header
# and Django will believe an insecure request was secure.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# --- HTTPS hardening (production only) ---
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS tells browsers to refuse plain HTTP for this domain, and they CACHE
    # that for the full duration — it cannot be undone by redeploying. Ramp it:
    # deploy at 3600 (1h), confirm every subdomain serves HTTPS, then raise to
    # 31536000 (1y) and only then consider INCLUDE_SUBDOMAINS / PRELOAD.
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool
    )
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'requester',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.spotify',
]

SITE_ID = 1

# Tell allauth to use your custom adapter pipeline
# Format: 'app_name.filename.ClassName'
SOCIALACCOUNT_ADAPTER = 'requester.adapters.SpotifySocialAdapter'

# Request basic profile permissions from the user's Spotify account
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = True
ACCOUNT_SIGNUP_REDIRECT_URL = '/dashboard/'

_FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
SOCIALACCOUNT_AUTHENTICATION_ERROR_URL = f'{_FRONTEND_URL}/?auth_error=true'

SOCIALACCOUNT_PROVIDERS = {
    'spotify': {
        'APP': {
            'client_id': config('SPOTIFY_CLIENT_ID'),
            'secret': config('SPOTIFY_CLIENT_SECRET'),
        },
        'SCOPE': [
            'user-read-private',
            'user-read-email',
            'user-modify-playback-state',
            'user-read-playback-state',
        ],
    }
}

# Redirect destinations after authentication
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Must come directly after SecurityMiddleware: serves collected static
    # files in production, since no web server sits in front of gunicorn.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'songforyou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'songforyou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# The database is Neon (managed serverless Postgres), addressed by a single
# DATABASE_URL. Prefer it when present; otherwise fall back to the discrete DB_*
# vars used for local development.
_DATABASE_URL = config('DATABASE_URL', default='')

if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            # Reuse connections rather than reconnecting per request. Neon
            # charges for compute time and connection setup is not free.
            conn_max_age=config('DB_CONN_MAX_AGE', default=600, cast=int),

            # REQUIRED for Neon. Neon suspends idle compute (~5 min on free
            # plans) and drops its connections. Without a health check Django
            # hands a pooled-but-dead connection to the next request, which
            # fails with 'server closed the connection unexpectedly' — the
            # classic symptom being that the first request after a quiet period
            # 500s and the retry succeeds. This pings before reuse and
            # transparently reconnects instead.
            conn_health_checks=True,

            # Neon terminates non-TLS connections. Its own connection string
            # already carries ?sslmode=require; this makes it fail closed even
            # if a URL is pasted in without it. Scoped to Postgres: sslmode is
            # not a valid connect() argument for sqlite, so applying it
            # unconditionally would break a local sqlite DATABASE_URL.
            ssl_require=_DATABASE_URL.startswith(('postgres://', 'postgresql://')),

            # Neon's pooled endpoint is PgBouncer in TRANSACTION pooling mode,
            # which cannot hold a server-side cursor open across statements.
            # Anything using QuerySet.iterator() would fail there with
            # 'cursor does not exist'. Django's documented remedy is to disable
            # them. Costs memory on very large result sets; nothing here is
            # large. Set DB_SERVER_SIDE_CURSORS=True only on a direct (non
            # -pooler) endpoint.
            disable_server_side_cursors=not config(
                'DB_SERVER_SIDE_CURSORS', default=False, cast=bool
            ),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Target for `manage.py collectstatic`. Required in production: with DEBUG=False
# Django no longer serves admin / DRF browsable-API assets itself.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # The manifest backend fingerprints filenames for cache-busting and
        # errors on any missing file — correct for production, but it would
        # break local dev before collectstatic has been run.
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Wide-open CORS is a development affordance only. In production, list the
# frontend origins explicitly via CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]