# Generated by Django 5.2.15 on 2026-06-08 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('recipient_tag', models.CharField(db_index=True, max_length=100)),
                ('trigger_type', models.CharField(choices=[('thought', 'Someone listened to this song and thought about you'), ('reminded', 'This song reminded someone of you')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('played', 'Played'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dj_name', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_tag', models.CharField(db_index=True, max_length=100)),
                ('message_text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requester.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='requester.session'),
        ),
    ]
