# Generated by Django 5.2.15 on 2026-06-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='album_art_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
