# Generated by Django 5.2.15 on 2026-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0004_session_dj'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
