# Generated by Django 5.2.15 on 2026-06-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0005_request_custom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
