# Generated by Django 5.2.15 on 2026-09-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_handle_recipients(apps, schema_editor):
    """
    Existing rows only ever stored a recipient as a tag string. Inboxes now match
    on recipient_user, so link the rows whose tag resolves to a real handle —
    without this those dedications would silently vanish from their recipients'
    inboxes. Tags that match nothing are left NULL: they become the
    'not on the app' case, which is exactly what they always were.
    """
    Request = apps.get_model('requester', 'Request')
    UserProfile = apps.get_model('requester', 'UserProfile')

    handles = {
        p.app_handle.lower(): p.user_id
        for p in UserProfile.objects.all()
    }
    # Deliberately not .iterator(): that opens a server-side cursor, which the
    # pooled Neon endpoint (PgBouncer, transaction mode) cannot keep open across
    # statements. This table is small, so a plain queryset is fine.
    updates = []
    for req in Request.objects.filter(recipient_user__isnull=True):
        user_id = handles.get((req.recipient_tag or '').lstrip('@').lower())
        if user_id is not None:
            req.recipient_user_id = user_id
            updates.append(req)

    if updates:
        Request.objects.bulk_update(updates, ['recipient_user'], batch_size=500)


def unlink(apps, schema_editor):
    """Reverse is a no-op: the column is dropped by the schema operation."""


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0006_request_spotify_track_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(link_existing_handle_recipients, unlink),
    ]
